//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightObesity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int RecipesID { get; set; }
        public string Breakfast { get; set; }
        public string Snack { get; set; }
        public string Lunch { get; set; }
        public string Dinner { get; set; }
    }
}
